# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8f33b252048d1488705f70864509ababd0de316ff6b8919f0c5c4fdef234cd494f1a048f7e9460adaa91bd94ffe3bf188e01766c4cd0c265a4ba71f654e91612

test:
  secret_key_base: fd9e9af540ca4bf3c097ebfc1396f2b97b16c708f5df887378b6c3a53190171ffe8b45a5cd1fcbdc94bc71628bfb5d08dca3721c05d123b444950cc3a598d6eb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
